name: 'Netlify Preview And Production Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy-preview:
    name: 'Deploy Preview'
    runs-on: ubuntu-latest

    steps:
      - name: deploy to preview mode
        uses: thundermiracle/netlify-deploy@v3.0.1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
          deploy-dir: "./public"
          extra-cache-path: |
            .cache
            public
          cache-strategy: npm
          install-command: npm install --production
          build-command: npm run build