name: Netlify Production Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: 'Deploy Production'
    runs-on: ubuntu-latest

    steps:
      - name: deploy to production mode
        uses: thundermiracle/netlify-deploy@v3
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN}}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID}}
          deploy-dir: "./public"
          extra-cache-path: |
            .cache
            public
          production: true
          cache-strategy: npm
          install-command: npm install --production
          build-command: npm run build